import classes from "./FAQ.module.css";
import Title from "./Title";
import back from "../assets/back5.png";
import ico from "../assets/faq-ico.svg";
import Wrapper from "./UI/Wrapper";

import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
} from "react-accessible-accordion";

const FAQ = () => {
  return (
    <section
      className={classes.faq}
      style={{ backgroundImage: `url(${back})` }}
      id="faq"
    >
      <Title text="Frequently asked questions" ico={ico} />
      <Wrapper>
        <Accordion allowZeroExpanded allowMultipleExpanded>
          <AccordionItem>
            <AccordionItemHeading>
              <AccordionItemButton>
                <p>Who are these Aliens?</p>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p>
                Alien Gang 51 is unique a collection of NFTs backed by the
                Solana blockchain. Each alien is a one-of-a-kind asset that is
                owned entirely by the purchaser.
              </p>
            </AccordionItemPanel>
          </AccordionItem>
          <AccordionItem>
            <AccordionItemHeading>
              <AccordionItemButton>
                <p>What is the total supply?</p>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p>
                The collection of images will consist of 5151 of our brothers,
                generated by unique software from more than 420 traits
              </p>
            </AccordionItemPanel>
          </AccordionItem>
          <AccordionItem>
            <AccordionItemHeading>
              <AccordionItemButton>
                <p>What is the mint price?</p>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p>Price is 0.75 SOL</p>
            </AccordionItemPanel>
          </AccordionItem>
          <AccordionItem>
            <AccordionItemHeading>
              <AccordionItemButton>
                <p>When can I mint one?</p>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p>General public sale is on Thursday, December 23rd, 2021</p>
            </AccordionItemPanel>
          </AccordionItem>
          <AccordionItem>
            <AccordionItemHeading>
              <AccordionItemButton>
                <p>Is there a mint limit?</p>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p>
                For users, a limit will be set on a one-time purchase of cards -
                no more than 51 (yes, we know that this is trivial) at a time,
                but how many such times there will be - it's up to you, our
                wonderful earthly friend
              </p>
            </AccordionItemPanel>
          </AccordionItem>
          <AccordionItem>
            <AccordionItemHeading>
              <AccordionItemButton>
                <p>What does DAO stand for?</p>
              </AccordionItemButton>
            </AccordionItemHeading>
            <AccordionItemPanel>
              <p>
                Decentralized autonomous organization. You should think about it
                as a democratic voting system within the blockchain. We are
                planning to use this system in progressing the project Based on
                the feedback and discussions of our members in social networks
                and chats, we will adjust the development of the project. We are
                going to add new social mechanics and change the current ones.
              </p>
            </AccordionItemPanel>
          </AccordionItem>
        </Accordion>
      </Wrapper>
    </section>
  );
};

export default FAQ;
